[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "geodin-ggf-date-tool"
version = "0.1.0"
description = "GUI tool to update GeoDIN GGF layout sampling dates from Excel."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openpyxl>=3.1.0"
    "tkinterdnd2>=0.4.2"
]

[tool.setuptools.packages.find]
where = ["src"]